vich_uploader:
    db_driver: orm

    mappings:
       montage_image:
           uri_prefix: /assets/images/montages
           upload_destination: '%kernel.project_dir%/public/assets/images/montages'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

       espece_image:
           uri_prefix: /assets/images/especes
           upload_destination: '%kernel.project_dir%/public/assets/images/especes'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
