<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZoD1n5X\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZoD1n5X/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZoD1n5X.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZoD1n5X\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZoD1n5X\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZoD1n5X',
    'container.build_id' => '802857e4',
    'container.build_time' => 1608800173,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZoD1n5X');
