<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDqSp80P\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDqSp80P/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDqSp80P.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDqSp80P\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDqSp80P\App_KernelDevDebugContainer([
    'container.build_hash' => 'DqSp80P',
    'container.build_id' => '9ce8acde',
    'container.build_time' => 1611665519,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDqSp80P');
