<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'espece_index' => [[], ['_controller' => 'App\\Controller\\EspeceController::index'], [], [['text', '/espece/index']], [], []],
    'espece_create' => [[], ['_controller' => 'App\\Controller\\EspeceController::create'], [], [['text', '/espece/create']], [], []],
    'espece_update' => [['id'], ['_controller' => 'App\\Controller\\EspeceController::create'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/espece/update']], [], []],
    'espece_delete' => [['id'], ['_controller' => 'App\\Controller\\EspeceController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/espece/delete']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'message_index' => [[], ['_controller' => 'App\\Controller\\MessageController::index'], [], [['text', '/message/index']], [], []],
    'message_create' => [[], ['_controller' => 'App\\Controller\\MessageController::create'], [], [['text', '/message/create']], [], []],
    'message_update' => [['id'], ['_controller' => 'App\\Controller\\MessageController::create'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/message/update']], [], []],
    'message_delete' => [['id'], ['_controller' => 'App\\Controller\\MessageController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/message/delete']], [], []],
    'montage_index' => [['espece_id'], ['espece_id' => null, '_controller' => 'App\\Controller\\MontageController::index'], [], [['variable', '/', '[^/]++', 'espece_id', true], ['text', '/montage/index']], [], []],
    'montage_create' => [[], ['_controller' => 'App\\Controller\\MontageController::create'], [], [['text', '/montage/create']], [], []],
    'montage_update' => [['id'], ['_controller' => 'App\\Controller\\MontageController::create'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/montage/update']], [], []],
    'montage_delete' => [['id'], ['_controller' => 'App\\Controller\\MontageController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/montage/delete']], [], []],
    'link_espece' => [['id', 'espece_id'], ['espece_id' => null, '_controller' => 'App\\Controller\\MontageController::linkEspece'], [], [['variable', '/', '[^/]++', 'espece_id', true], ['variable', '/', '[^/]++', 'id', true], ['text', '/montage/link']], [], []],
    'unlink_espece' => [['id', 'espece_id'], ['_controller' => 'App\\Controller\\MontageController::unlinkEspece'], [], [['variable', '/', '[^/]++', 'espece_id', true], ['variable', '/', '[^/]++', 'id', true], ['text', '/montage/unlink']], [], []],
];
